enable-unenchant-button: true

enchantments:
  arrow-damage:
    level1: 4
    level2: 8
    level3: 12
    level4: 16
    
  arrow-fire:
    level1: 4
    level2: 8
    level3: 12
    level4: 16
    
  arrow-infinite:
    level1: 4
    level2: 8
    level3: 12
    level4: 16
    
  arrow-knockback:
    level1: 4
    level2: 8
    level3: 12
    level4: 16
    
  damage-all:
    level1: 4
    level2: 8
    level3: 12
    level4: 16
    
  damage-arthropods:
    level1: 4
    level2: 8
    level3: 12
    level4: 16
    
  damage-undead:
    level1: 4
    level2: 8
    level3: 12
    level4: 16
    
  dig-speed:
    level1: 4
    level2: 8
    level3: 12
    level4: 16
    
  durability:
    level1: 4
    level2: 8
    level3: 12
    level4: 16
    
  fire-aspect:
    level1: 4
    level2: 8
    level3: 12
    level4: 16
  
  knockback:
    level1: 4
    level2: 8
    level3: 12
    level4: 16
    
  loot-bonus-blocks:
    level1: 4
    level2: 8
    level3: 12
    level4: 16
    
  loot-bonus-mobs:
    level1: 4
    level2: 8
    level3: 12
    level4: 16
  
  oxygen:
    level1: 4
    level2: 8
    level3: 12
    level4: 16
    
  protection-environmental:
    level1: 4
    level2: 8
    level3: 12
    level4: 16
  
  protection-explosions:
    level1: 4
    level2: 8
    level3: 12
    level4: 16
    
  protection-fall:
    level1: 4
    level2: 8
    level3: 12
    level4: 16
    
  protection-fire:
    level1: 4
    level2: 8
    level3: 12
    level4: 16
  
  protection-projectile:
    level1: 4
    level2: 8
    level3: 12
    level4: 16
    
  silk-touch:
    level1: 4
    level2: 8
    level3: 12
    level4: 16
    
  thorns:
    level1: 4
    level2: 8
    level3: 12
    level4: 16
  
  water-worker:
    level1: 4
    level2: 8
    level3: 12
    level4: 16
